### ISSUE TITLE
[Panache Drive] List files owned by user

### ISSUE THREAD

**Issue by alexisbouchez** [PanacheApp/panache#3]
### Description

Once a user has started to upload his files, he needs to see them, and be able to rename/delete those.

A user should be allowed to navigate into the different folders inside of his storage bucket (accessible through Panache Drive).

And he should see the different files in the folders, their name, type, file size, and creation timestamp.

### Tasks

- [ ] Allows users to see the list of files inside a current folder, with the following fields
  - Name
  - Type
  - Creation date
  - Last Update date

- [ ] Allow users to navigate between folders, and visualize which folder they are browsing
- [ ] Allow users to rename their files
- [ ] Allow users to rename their folders
- [ ] Allow users to delete their files
- [ ] Allow users to delete their folders

PS: We can breakdown this issue further if needed, feel free to ask for more details if needed.
